apiVersion: v1
kind: Deployment
metadata:
  name: deployment-01
  labels:
    app: deployment-01
spec:
  replicas: 7
  selector:
    matchLabels:
      app: example-k8s-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-k8s-pod
        language: go
    spec:
      containers:
      - name: example-k8s
        image: ghcr.io/aestebance/practica-go-kubernetes:v1.0.7
        env:
          - name: ANIMAL
            value: "perro"