apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  containers:
    - name: example-k8s
      image: ghcr.io/aestebance/practica-go-kubernetes:v1.0.7
      env:
        - name: ANIMAL
          value: "perro"
        - name: SLEEP_TIME
          value: "5s"
