apiVersion: v1
kind: ReplicaSet
metadata:
  name: replicaSet-01
  labels:
    app: replicaSet-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-k8s-pod
  template:
    metadata:
      labels:
        app: example-k8s-pod
        language: go
    spec:
      containers:
      - name: example-k8s
        image: ghcr.io/aestebance/practica-go-kubernetes:v1.0.6